
import Head from 'next/head'
const Layout = ({children}) => {
  return (
    <div>

<Head>
        <title>Guitar Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <h1>Desde Layout</h1>
        {children}
    </div>
  )
}

export default Layout